version: '3.9'

services:
  ai-app:
    container_name: AI
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8008:8000"
    env_file:
     - .env