- name: snowflake
  hosts: model_instance
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars_files:
    - vars/vault.yml
    - vars/all.yml
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_private_key_file: /ansible/snow
  roles: 
   - model
  tags: 
    - model