version: '3.9'

services:
  ai-app-ml2:
    container_name: AI2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8007:8000"
    env_file:
     - .env
    